# Generated by Django 4.1.7 on 2023-05-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmap', '0002_geoinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoinformation',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='geoinformation',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
