# Generated by Django 4.1.7 on 2023-05-04 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmap', '0005_remove_centerlist_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centerlist',
            name='address',
        ),
    ]
